"""
Semantic Ad Matcher

Part 2 of the two-part pipeline: given the LLM response text and the Commercial
Intents (CIs) generated by constrained beam search, find which CIs are
semantically relevant to the response.

Matching steps:
  1. Embed the response using mean-pooled last hidden states of the Qwen model
  2. Embed each CI phrase the same way
  3. Compute cosine similarity between response and CI embeddings
  4. Keep only CIs above a configurable threshold (default: 0.70)
  5. Deduplicate by product_id (keep highest-scoring CI per product)
  6. Cap at max_ads (default: 2)

Reuses the already-loaded Qwen model — no second model load.
"""

import json
import torch
import torch.nn.functional as F
from dataclasses import dataclass
from typing import Optional

from src.constrained_decoder import CIResult


@dataclass
class MatchedAd:
    """An ad that matched the response above the similarity threshold."""
    product_id: str
    title: str
    brand: str
    category: str
    description: str
    url: str
    price: Optional[float]
    ci_text: str        # The CI that triggered this ad
    match_score: float  # Cosine similarity (0–1)


def _embed(model, tokenizer, device: torch.device, text: str) -> torch.Tensor:
    """Mean-pool last hidden states to produce a sentence embedding."""
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512,
        add_special_tokens=True,
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True)

    last_hidden = outputs.hidden_states[-1]  # [1, seq_len, hidden_dim]
    attention_mask = inputs["attention_mask"].unsqueeze(-1).float()
    pooled = (last_hidden * attention_mask).sum(dim=1) / attention_mask.sum(dim=1)
    return F.normalize(pooled, dim=-1)


def match_ads(
    response_text: str,
    ci_results: list,
    ci_ad_index_path: str,
    model,
    tokenizer,
    device: torch.device,
    threshold: float = 0.70,
    max_ads: int = 2,
) -> list:
    """
    Match ads to the LLM response by comparing CI embeddings to the response embedding.

    Args:
        response_text: The vanilla LLM response (Part 1 output).
        ci_results: CIs from constrained beam search (list of CIResult).
        ci_ad_index_path: Path to ci_ad_index.json.
        model: Loaded Qwen model (shared with constrained decoder).
        tokenizer: Corresponding tokenizer.
        device: torch.device the model lives on.
        threshold: Minimum cosine similarity to include an ad (default 0.70).
        max_ads: Maximum number of ads to return (default 2).

    Returns:
        List of MatchedAd objects sorted by match_score descending, capped at max_ads.
    """
    if not ci_results or not response_text.strip():
        return []

    with open(ci_ad_index_path) as f:
        ci_ad_index = json.load(f)

    response_emb = _embed(model, tokenizer, device, response_text)

    seen_products: dict = {}  # product_id → MatchedAd; keeps best score per product

    for ci in ci_results:
        ads = ci_ad_index.get(ci.ci_text, [])
        if not ads:
            continue

        ci_emb = _embed(model, tokenizer, device, ci.ci_text)
        similarity = float(F.cosine_similarity(response_emb, ci_emb, dim=-1).item())

        if similarity < threshold:
            continue

        for ad in ads:
            pid = ad["product_id"]
            if pid in seen_products and seen_products[pid].match_score >= similarity:
                continue  # Already have a better match for this product

            seen_products[pid] = MatchedAd(
                product_id=pid,
                title=ad["title"],
                brand=ad["brand"],
                category=ad["category"],
                description=ad["description"],
                url=ad["url"],
                price=ad.get("price"),
                ci_text=ci.ci_text,
                match_score=similarity,
            )

    matched = sorted(seen_products.values(), key=lambda a: a.match_score, reverse=True)
    return matched[:max_ads]
